- hosts: worker
  become: yes
  tasks:

  - name: Create temporal kubeadm dir
    file:
      path: "{{ kubeadm_dir }}"
      state: directory

  - name: Render Join Config File
    template:
      src: templates/join-worker-config.j2
      dest: "{{ kubeadm_dir }}/config.yaml"
  
  - name: Kubeadm Join Worker
    shell: kubeadm join --config {{ kubeadm_dir }}/config.yaml 

  - name: Label Nodes as workers
    become: no
    k8s:
      definition:
        api_version: v1
        kind: Node
        metadata:
          name: "{{ inventory_hostname }}"
          labels:
            node-role.kubernetes.io/worker: ""
    delegate_to: localhost

  - name: Delete Kubeadm dir
    file:
      path: "{{ kubeadm_dir }}"
      state: absent
